In [1]:
# Dependencies 
import pandas as pd
import matplotlib as plt

In [2]:
# Files to load
immigration_file_to_load = (r"C:\Users\bayek\OneDrive\Documents\GitHub\Project-1-DeskTop\canadian_immegration_data.csv")

In [3]:
# Read the files and study the results 
immigration_metadata = pd.read_csv(immigration_file_to_load)

In [4]:
# Display CSV
immigration_metadata.head()

,Country,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1223,856,702,560,716,561,539,620,603,15699
2,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,69439
3,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,6
4,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,1,1,0,0,0,0,1,1,15